### ISSUE TITLE
Conda package

### ISSUE THREAD

**Issue by natct10** [SubstraFoundation/distributed-learning-contributivity#229] opened 2020-09-09 09:48 UTC
https://docs.conda.io/projects/conda-build/en/latest/user-guide/tutorials/build-pkgs.html

**Comment by bowni** [comment] 2020-09-14 16:35
@natct10 isn't this issue a duplicate of #212 ?

**Comment by natct10** [comment] 2020-09-16 10:13
> @natct10 isn't this issue a duplicate of #212 ?

You're right!

**Closed** 2020-10-20 13:03 UTC
